import '/material/components/title/material-title.js';

import './views/aside/view-aside.js';

import './pages/default/page-default.js';

import './pages/button/page-button.js';
import './pages/input/page-input.js';
import './pages/select/page-select.js';
import './pages/toggle/page-toggle.js';
import './pages/chips/page-chips.js';
import './pages/expand/page-expand.js';
import './pages/tabs/page-tabs.js';
import './pages/title/page-title.js';
import './pages/paper/page-paper.js';
import './pages/list/page-list.js';
import './pages/drop/page-drop.js';
import './pages/tooltip/page-tooltip.js';
import './pages/breadcrumbs/page-breadcrumbs.js';
import './pages/message/page-message.js';
import './pages/card/page-card.js';
import './pages/badge/page-badge.js';
import './pages/icon/page-icon.js';
import './pages/blockquote/page-blockquote.js';
import './pages/figure/page-figure.js';
import './pages/loader/page-loader.js';
import './pages/progress/page-progress.js';
import './pages/table/page-table.js';
import './pages/search/page-search.js';
import './pages/dialog/page-dialog.js';
import './pages/grid/page-grid.js';
import './pages/header/page-header.js';
import './pages/footer/page-footer.js';
import './pages/copyright/page-copyright.js';
import './pages/parallax/page-parallax.js';
import './pages/panorama/page-panorama.js';
import './pages/calendar/page-calendar.js';
import './pages/payment/page-payment.js';
import './pages/navigation/page-navigation.js';
import './pages/avatar/page-avatar.js';
import './pages/sheet/page-sheet.js';
// import './pages/camera/page-camera.js';
import './pages/caption/page-caption.js';
import './pages/text/page-text.js';
